spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URI:postgres:5432}/authentication_db
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  secret: n4EpjnNy7x8FjfwYMDjPi8xYyL0EocN1uzUsfFTbLhk=
  expiration: 86400

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:
        defaultZone: http://${EUREKA_URI:eureka-service:8761}/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true