spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/core_book_db
    username: postgres  
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/

queue:
  name: queue-1

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true