spring:
  datasource:
    url: jdbc:postgresql://core-service-postgres:5432/core_service_db
    username: postgres  
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/microservices-app-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    username: guest
    password: guest
    port: ${RABBIT_PORT:5672}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:eureka-service:8761}/eureka/

queue:
  name: queue-1

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true