spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: core_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/book/**
        - id: auth_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/auth/**
        - id: role_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/roles/**
        - id: groups_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/groups/**
        - id: users_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/users/**
        - id:  library_route
          uri: lb://library-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/library/**
        - id:  library_health_route
          uri: lb://library-service
          predicates:
            - name: Path
              args:
                pattern: /library-service/actuator/health
        - id:  core_health_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /core-service/actuator/health
        - id:  auth_health_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /auth-service/actuator/health
        - id: core_swagger_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /core-service/swagger-ui/**
        - id: core_api_docs_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /core-service/v3/api-docs/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/microservices-app-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Core Service
        url: /core-service/swagger-ui/index.html
      - name: Library Service
        url: /library-service/swagger-ui/index.html
      - name: Auth Service
        url: /auth-service/swagger-ui/index.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/