spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: core_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/book/**
          filters:
            - name: CircuitBreaker
              args:
                name: core-service-circuit
                fallbackUri: redirect:/fallback/core-service
        - id: auth_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service-circuit
                fallbackUri: redirect:/fallback/auth-service
        - id: role_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/roles/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service-circuit
                fallbackUri: redirect:/fallback/auth-service
        - id: groups_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/groups/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service-circuit
                fallbackUri: redirect:/fallback/auth-service
        - id: users_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service-circuit
                fallbackUri: redirect:/fallback/auth-service
        - id:  library_route
          uri: lb://library-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/library/**
          filters:
            - name: CircuitBreaker
              args:
                name: library-service-circuit
                fallbackUri: redirect:/fallback/library-service
        - id:  library_health_route
          uri: lb://library-service
          predicates:
            - name: Path
              args:
                pattern: /library-service/actuator/health
        - id:  core_health_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /core-service/actuator/health
        - id:  auth_health_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /auth-service/actuator/health
        - id:  core_check_port_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /core-service/service-health/**
        - id: core_swagger_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /core-service-docs/**
        - id: auth_swagger_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /auth-service-docs/**
        - id: library_swagger_route
          uri: lb://library-service
          predicates:
            - name: Path
              args:
                pattern: /library-service-docs/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/microservices-app-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Core Service
        url: /core-service-docs/swagger-ui/index.html
      - name: Library Service
        url: /library-service-docs/swagger-ui/index.html
      - name: Auth Service
        url: /auth-service-docs/swagger-ui/index.html

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 3

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/
