spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: core_route
          uri: lb://core-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/book/**
        - id: auth_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/auth/**
        - id: role_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/roles/**
        - id: groups_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/groups/**
        - id: users_route
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/users/**
        - id:  library_route
          uri: lb://library-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/library/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/test-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/